Repository shapeshift/web, pull requests merged in 2022-04, with the labels that each got.

#1179 feat: portfolio refresh on new tx
  cypress/integration/dashboard_spec.ts
  cypress/support/commands.ts
  src/context/PortfolioProvider/PortfolioContext.tsx
  src/state/slices/portfolioSlice/portfolioSlice.ts
  src/state/slices/txHistorySlice/txHistorySlice.test.ts
  src/state/slices/txHistorySlice/txHistorySlice.ts
  src/state/slices/txHistorySlice/utils.test.ts
  src/state/slices/txHistorySlice/utils.ts
Labels: blocker

#1341 feat: add keepkey settings & initialize flow
  headers.js
  package.json
  sample.env
  src/AppProviders.tsx
  src/assets/translations/main.json
  src/components/Alert/Alert.theme.ts
  src/components/Graph/TimeControls.tsx
  src/components/Layout/Header/NavBar/ExpandedMenuItem.tsx
  src/components/Layout/Header/NavBar/KeepKey/AwaitKeepKey.tsx
  src/components/Layout/Header/NavBar/KeepKey/ChangeLabel.tsx
  src/components/Layout/Header/NavBar/KeepKey/ChangePassphrase.tsx
  src/components/Layout/Header/NavBar/KeepKey/ChangePin.tsx
  src/components/Layout/Header/NavBar/KeepKey/ChangePinCaching.tsx
  src/components/Layout/Header/NavBar/KeepKey/ChangeTimeout.tsx
  src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
  src/components/Layout/Header/NavBar/KeepKey/LastDeviceInteractionStatus.tsx
  src/components/Layout/Header/NavBar/KeepKey/Modals/Wipe.tsx
  src/components/Layout/Header/NavBar/SubMenuBody.tsx
  src/components/Layout/Header/NavBar/SubMenuContainer.tsx
  src/components/Layout/Header/NavBar/SubmenuHeader.tsx
  src/components/Layout/Header/NavBar/UserMenu.tsx
  src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
  src/components/Layout/Header/NavBar/WalletImage.tsx
  src/components/Layout/Header/NavBar/hooks/useMenuRoutes.ts
  src/components/Radio/Radio.tsx
  src/config.ts
  src/context/ModalProvider/ModalProvider.tsx
  src/context/WalletProvider/KeepKey/components/Label.tsx
  src/context/WalletProvider/KeepKey/components/Passphrase.tsx
  src/context/WalletProvider/KeepKey/components/Pin.tsx
  src/context/WalletProvider/KeepKey/components/RecoverySentence.tsx
  src/context/WalletProvider/KeepKey/components/WipedSuccessfully.tsx
  src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
  src/context/WalletProvider/KeepKey/hooks/useKeepKeyVersions.ts
  src/context/WalletProvider/KeepKeyProvider.tsx
  src/context/WalletProvider/WalletContext.tsx
  src/context/WalletProvider/WalletProvider.tsx
  src/context/WalletProvider/WalletViewsSwitch.tsx
  src/context/WalletProvider/actions.ts
  src/context/WalletProvider/config.ts
  src/context/WalletProvider/routes.ts
  src/hooks/useWallet/useWallet.tsx
  src/state/slices/preferencesSlice/preferencesSlice.ts
  src/test/mocks/store.ts
  yarn.lock
Labels: needs operations

#1452 refactor: split foxy, yearn deposit and withdraw into multiple components
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositCommon.ts
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositContext.ts
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositReducer.ts
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/FoxyDeposit.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Status.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/FoxyWithdraw.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawCommon.ts
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawContext.ts
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/WithdrawReducer.ts
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Approve.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Status.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Withdraw/components/Withdraw.tsx
  src/features/defi/providers/yearn/components/YearnManager/Deposit/DepositCommon.ts
  src/features/defi/providers/yearn/components/YearnManager/Deposit/DepositContext.ts
  src/features/defi/providers/yearn/components/YearnManager/Deposit/DepositReducer.ts
  src/features/defi/providers/yearn/components/YearnManager/Deposit/YearnDeposit.tsx
  src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx
  src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Status.tsx
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/WithdrawCommon.ts
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/WithdrawContext.ts
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/WithdrawReducer.ts
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/YearnWithdraw.tsx
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Status.tsx
  src/features/defi/providers/yearn/components/YearnManager/Withdraw/components/Withdraw.tsx
  src/features/defi/providers/yearn/components/YearnManager/YearnManager.tsx
Labels: needs operations

#1510 fix: directly redirect to dashboard when connecting to a wallet
  src/context/WalletProvider/KeepKey/components/Connect.tsx
  src/context/WalletProvider/MetaMask/components/Connect.tsx
  src/context/WalletProvider/MetaMask/components/Success.tsx
  src/context/WalletProvider/Portis/components/Connect.tsx
  src/context/WalletProvider/Portis/components/Success.tsx
  src/context/WalletProvider/config.ts
Labels: needs operations

#1593 chore: bump chain-adapters
  package.json
  yarn.lock
Labels: needs operations

#1566 feat: error on fiat balance lower than fiat-ramp provider minimum usd
  src/assets/translations/main.json
  src/components/Modals/FiatRamps/FiatRampsCommon.ts
  src/components/Modals/FiatRamps/config.ts
  src/components/Modals/FiatRamps/hooks/useFiatRampCurrencyList.ts
  src/components/Modals/FiatRamps/views/Overview.tsx
Labels: needs product
