Repository shapeshift/web, pull requests merged in 2022-08, with the labels that each got.

#2284 feat: fiat ramp back button
  src/components/Modals/FiatRamps/FiatRamps.tsx
  src/components/Modals/FiatRamps/views/AssetSelect.tsx
Labels: needs operations

#2285 fix: multi-currency leftovers
  src/components/Trade/TradeInput.tsx
  src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.ts
  src/state/slices/marketDataSlice/selectors.ts
Labels: needs operations

#2298 feat: cosmos defi UI part 6: remove old cosmos staking
  src/context/ModalProvider/ModalProvider.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Claim/ClaimConfirm.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Withdraw.tsx
  src/plugins/cosmos/components/AmountToStake/AmountToStake.tsx
  src/plugins/cosmos/components/AssetClaimCard/AssetClaimCard.tsx
  src/plugins/cosmos/components/AssetHoldingsCard/AssetHoldingsCard.tsx
  src/plugins/cosmos/components/ClaimButton/ClaimButton.tsx
  src/plugins/cosmos/components/CosmosActionButtons/CosmosActionButtons.tsx
  src/plugins/cosmos/components/EstimatedReturnsRow/EstimatedReturnsRow.tsx
  src/plugins/cosmos/components/PercentOptionsRow/PercentOptionsRow.tsx
  src/plugins/cosmos/components/StakedRow/StakedRow.tsx
  src/plugins/cosmos/components/StakingInput/StakingInput.tsx
  src/plugins/cosmos/components/TxFeeRadioGroup/TxFeeRadioGroup.tsx
  src/plugins/cosmos/components/UnbondingRow/UnbondingRow.tsx
  src/plugins/cosmos/components/modals/Staking/Staking.tsx
  src/plugins/cosmos/components/modals/Staking/StakingCommon.ts
  src/plugins/cosmos/components/modals/Staking/forms/StakeFormManager.tsx
  src/plugins/cosmos/components/modals/Staking/views/ClaimBroadcast.tsx
  src/plugins/cosmos/components/modals/Staking/views/ClaimConfirm.tsx
  src/plugins/cosmos/components/modals/Staking/views/GetStarted/GetStarted.tsx
  src/plugins/cosmos/components/modals/Staking/views/GetStarted/GetStartedCommon.ts
  src/plugins/cosmos/components/modals/Staking/views/GetStarted/GetStartedManager.tsx
  src/plugins/cosmos/components/modals/Staking/views/GetStarted/LearnMore.tsx
  src/plugins/cosmos/components/modals/Staking/views/Overview.tsx
  src/plugins/cosmos/components/modals/Staking/views/Stake.tsx
  src/plugins/cosmos/components/modals/Staking/views/StakeBroadcast.tsx
  src/plugins/cosmos/components/modals/Staking/views/StakeConfirm.tsx
  src/plugins/cosmos/components/modals/Staking/views/Unstake.tsx
  src/plugins/cosmos/components/modals/Staking/views/UnstakeBroadcast.tsx
  src/plugins/cosmos/components/modals/Staking/views/UnstakeConfirm.tsx
  src/plugins/cosmos/utils.ts
Labels: needs operations

#2257 feat: show symbol on approval
  package.json
  src/components/TransactionHistoryRows/TransactionContract.tsx
  yarn.lock
Labels: blocker

#2419 feat: add allowance switch on swap, foxy and yearn
  package.json
  src/assets/translations/en/main.json
  src/components/Approval/Approval.tsx
  src/components/Trade/Trade.tsx
  src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
  src/components/Trade/hooks/useSwapper/useSwapper.ts
  src/components/Trade/types.ts
  src/features/defi/components/Approve/Approve.tsx
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositCommon.ts
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/DepositReducer.ts
  src/features/defi/providers/foxy/components/FoxyManager/Deposit/components/Approve.tsx
  src/features/defi/providers/yearn/components/YearnManager/Deposit/DepositCommon.ts
  src/features/defi/providers/yearn/components/YearnManager/Deposit/DepositReducer.ts
  src/features/defi/providers/yearn/components/YearnManager/Deposit/components/Approve.tsx
  yarn.lock
Labels: needs product

#2449 fix: lp-related balance bug fix and performance improvements
  src/AppProviders.tsx
  src/components/StakingVaults/AllEarnOpportunities.tsx
  src/components/StakingVaults/EarnOpportunities.tsx
  src/context/FoxEthProvider/FoxEthProvider.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Approve.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Status.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingDetails.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Approve.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Status.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx
  src/pages/Dashboard/Portfolio.tsx
  src/pages/Defi/components/OverviewHeader.tsx
  src/pages/Defi/hooks/useEarnBalances.tsx
  src/pages/Defi/hooks/useFoxEthLpBalances.tsx
  src/pages/Defi/hooks/useFoxFarmingBalances.tsx
  src/pages/Defi/views/Overview.tsx
  src/plugins/foxPage/hooks/useDefiOpportunity.ts
Labels: needs operations

#2496 feat: fox farming old contracts
  src/assets/translations/en/main.json
  src/components/StakingVaults/AllEarnOpportunities.tsx
  src/components/StakingVaults/EarnOpportunities.tsx
  src/components/StakingVaults/StakingTable.tsx
  src/context/FoxEthProvider/FoxEthProvider.tsx
  src/features/defi/components/Overview/Overview.tsx
  src/features/defi/components/Withdraw/Withdraw.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingDetails.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/WithdrawCard.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/WithdrawCommon.ts
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/ExpiredWithdraw.tsx
  src/features/defi/providers/fox-farming/constants.ts
  src/pages/Defi/components/OpportunityCard.tsx
  src/pages/Defi/hooks/useEarnBalances.tsx
  src/pages/Defi/views/StakingVaults.tsx
  src/plugins/foxPage/hooks/useOtherOpportunities.ts
Labels: needs operations

#2566 feat: store account metadata in portfolioSlice
  package.json
  src/context/AppProvider/AppContext.tsx
  src/state/slices/portfolioSlice/__snapshots__/portfolioSlice.test.ts.snap
  src/state/slices/portfolioSlice/portfolioSlice.ts
  src/state/slices/portfolioSlice/portfolioSliceCommon.ts
  src/state/slices/portfolioSlice/selectors.ts
  src/state/slices/portfolioSlice/utils.ts
  src/test/mocks/store.ts
  yarn.lock
Labels: multiple accounts

#2580 feat: receive address account number
  src/components/Modals/Receive/ReceiveInfo.tsx
  src/state/slices/portfolioSlice/selectors.ts
Labels: multiple accounts

#2344 feat: idle finance
  .env.base
  package.json
  react-app-rewired/headers/csps/defi/idle.ts
  src/assets/translations/en/main.json
  src/components/StakingVaults/AllEarnOpportunities.tsx
  src/components/StakingVaults/EarnOpportunities.tsx
  src/config.ts
  src/features/defi/components/DefiActionButtons.tsx
  src/features/defi/components/Overview/Overview.tsx
  src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
  src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx
  src/features/defi/contexts/IdleProvider/IdleProvider.tsx
  src/features/defi/contexts/IdleProvider/idleInvestorSingleton.ts
  src/features/defi/helpers/normalizeOpportunity.tsx
  src/features/defi/providers/idle/components/IdleManager/Claim/ClaimCommon.ts
  src/features/defi/providers/idle/components/IdleManager/Claim/ClaimContext.ts
  src/features/defi/providers/idle/components/IdleManager/Claim/ClaimReducer.ts
  src/features/defi/providers/idle/components/IdleManager/Claim/IdleClaim.tsx
  src/features/defi/providers/idle/components/IdleManager/Claim/components/ClaimableAsset.tsx
  src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx
  src/features/defi/providers/idle/components/IdleManager/Claim/components/Status.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/DepositCommon.ts
  src/features/defi/providers/idle/components/IdleManager/Deposit/DepositContext.ts
  src/features/defi/providers/idle/components/IdleManager/Deposit/DepositReducer.ts
  src/features/defi/providers/idle/components/IdleManager/Deposit/IdleDeposit.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Status.tsx
  src/features/defi/providers/idle/components/IdleManager/IdleManager.tsx
  src/features/defi/providers/idle/components/IdleManager/Overview/IdleOverview.tsx
  src/features/defi/providers/idle/components/IdleManager/Withdraw/IdleWithdraw.tsx
  src/features/defi/providers/idle/components/IdleManager/Withdraw/WithdrawCommon.ts
  src/features/defi/providers/idle/components/IdleManager/Withdraw/WithdrawContext.ts
  src/features/defi/providers/idle/components/IdleManager/Withdraw/WithdrawReducer.ts
  src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Status.tsx
  src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Withdraw.tsx
  src/hooks/useSortedVaults/useSortedVaults.test.ts
  src/hooks/useSortedVaults/useSortedVaults.ts
  src/hooks/useVaultWithoutBalance/useVaultWithoutBalance.ts
  src/pages/Defi/components/OpportunityCard.tsx
  src/pages/Defi/hooks/useEarnBalances.tsx
  src/pages/Defi/hooks/useVaultBalances.tsx
  src/state/slices/preferencesSlice/preferencesSlice.ts
  src/test/mocks/store.ts
  src/test/mocks/vaults.ts
  yarn.lock
Labels: needs operations
