Repository shapeshift/web, pull requests merged in 2022-09, with the labels that each got.

#2700 refactor: derive account ids and metadata abstraction
  src/context/AppProvider/AppContext.tsx
  src/lib/account/account.ts
  src/lib/account/cosmosSdk.ts
  src/lib/account/evm.ts
  src/lib/account/utxo.ts
Labels: multiple accounts

#2589 feat: move KeepKey's pin changing behavior to the wallet menu
  src/assets/translations/en/main.json
  src/components/Layout/Header/NavBar/KeepKey/ChangePin.tsx
  src/components/Layout/Header/NavBar/SubmenuHeader.tsx
  src/context/WalletProvider/KeepKey/KeepKeyTypes.ts
  src/context/WalletProvider/KeepKey/components/Pin.tsx
  src/context/WalletProvider/KeepKey/components/PinModal.tsx
  src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
  src/context/WalletProvider/WalletProvider.tsx
  src/context/WalletProvider/actions.ts
  src/context/WalletProvider/config.ts
Labels: keepkey-bounty

#2788 feat(mobile): add import via ShapeShift login
  src/context/WalletProvider/MobileWallet/components/Captcha.tsx
  src/context/WalletProvider/MobileWallet/components/MobileCreate.tsx
  src/context/WalletProvider/MobileWallet/components/MobileCreateTest.tsx
  src/context/WalletProvider/MobileWallet/components/MobileLegacyCreate.tsx
  src/context/WalletProvider/MobileWallet/components/MobileLegacyLogin.tsx
  src/context/WalletProvider/MobileWallet/components/MobileLegacySuccess.tsx
  src/context/WalletProvider/MobileWallet/components/MobileStart.tsx
  src/context/WalletProvider/MobileWallet/mobileMessageHandlers.ts
  src/context/WalletProvider/NativeWallet/components/LegacyMigration/Captcha.tsx
  src/context/WalletProvider/NativeWallet/components/LegacyMigration/LegacyLogin.tsx
  src/context/WalletProvider/NativeWallet/components/LegacyMigration/LegacyLoginSuccess.tsx
  src/context/WalletProvider/NativeWallet/components/LegacyMigration/types.ts
  src/context/WalletProvider/NativeWallet/components/NativeLegacyLogin.tsx
  src/context/WalletProvider/NativeWallet/components/NativeLegacySuccess.tsx
  src/context/WalletProvider/NativeWallet/types.ts
  src/context/WalletProvider/SelectModal.tsx
  src/context/WalletProvider/config.ts
  src/lib/cryptography/login.ts
Labels: migration

#2842 feat(swapper): add RUNE swaps support
  package.json
  src/components/Trade/TradeConfirm/TradeConfirm.tsx
  src/components/Trade/hooks/useSwapper/useSwapper.tsx
  src/components/Trade/hooks/useSwapper/utils.ts
  src/components/Trade/hooks/useTradeQuoteService.tsx
  src/state/slices/portfolioSlice/utils.ts
  yarn.lock
Labels: migration

#2885 feat: remove ChainIdType
  src/components/Modals/FiatRamps/views/Manager.tsx
  src/components/Modals/FiatRamps/views/Overview.tsx
  src/state/slices/portfolioSlice/utils.ts
Labels: migration

#2887 feat: bump swapper to latest
  package.json
  yarn.lock
Labels: migration

#2893 feat: rune swapping confirmed state
  src/components/Trade/TradeConfirm/TradeConfirm.tsx
  src/components/Trade/hooks/useTradeAmounts.tsx
Labels: migration

#2912 fix: gas fee base unit
  src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
  src/components/Trade/TradeConfirm/TradeConfirm.tsx
  src/components/Trade/TradeInputV2.tsx
  src/components/Trade/hooks/useSwapper/useSwapper.tsx
  src/components/Trade/hooks/useSwapper/utils.ts
  src/components/Trade/types.ts
  src/test/constants.ts
Labels: migration

#2913 feat: balance chart asset list of color
  src/assets/translations/en/main.json
  src/components/AssetAccountDetails.tsx
  src/components/AssetHeader/AssetChart.tsx
  src/components/MaybeChartUnavailable.tsx
  src/hooks/useBalanceChartData/useBalanceChartData.ts
  src/hooks/useBalanceChartData/utils.ts
  src/pages/Dashboard/Portfolio.tsx
  src/plugins/cosmos/CosmosAssetAccountDetails.tsx
Labels: migration

#2909 chore: bump caip remove hegic from thor pools
  package.json
  yarn.lock
Labels: migration
