Repository shapeshift/web, pull requests merged in 2022-10, with the labels that each got.

#2930 fix: allow pendo track events through request filter
  src/plugins/pendo/agent/filters.ts
Labels: migration

#2918 fix: clear stale values on asset toggle
  src/components/Trade/TradeInputV2.tsx
  src/components/Trade/hooks/useGetTradeAmounts.tsx
  src/components/Trade/hooks/useTradeAmounts.tsx
  src/components/Trade/types.ts
Labels: migration

#2932 fix: swapper default assets
  src/components/Trade/Trade.tsx
  src/components/Trade/TradeRoutes/TradeRoutes.tsx
  src/components/Trade/hooks/useDefaultAssets.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Trade/Trade.tsx
Labels: migration

#2931 feat(mobile): support seed phrase recovery for the mobile app
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseCommon.ts
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseInfo.tsx
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseModal.tsx
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphrasePassword.tsx
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseRouter.tsx
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseStart.tsx
  src/components/Layout/Header/NavBar/Native/BackupPassphraseModal/BackupPassphraseTest.tsx
  src/context/WalletProvider/WalletProvider.tsx
  src/context/WalletProvider/config.ts
Labels: migration

#2950 fix: partially unrug max button
  src/components/Trade/hooks/useTradeQuoteService.tsx
Labels: migration

#2938 fix: buy asset amount calculations
  src/components/Trade/TradeConfirm/TradeConfirm.tsx
  src/components/Trade/TradeInputV2.tsx
  src/components/Trade/hooks/useGetTradeAmounts.tsx
Labels: migration

#2951 fix: update trade loading state and dropdown placement
  src/components/DeFi/components/AssetInput.tsx
  src/components/Modals/FiatRamps/components/FiatRampButton.tsx
  src/components/Modals/Receive/ReceiveInfo.tsx
Labels: migration

#2971 feat: disable swapper with message overlay for Keplr
  src/assets/translations/en/main.json
  src/components/MessageOverlay/MessageOverlay.tsx
  src/pages/Dashboard/TradeCard.tsx
Labels: migration

#2970 feat: enable thorchain for mobile only hack
  .env.base
  .env.dev
  src/config.ts
Labels: migration

#2939 feat: consolidate cosmos form and useFormSend
  src/components/Modals/Send/Form.tsx
  src/components/Modals/Send/SendCommon.tsx
  src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
  src/plugins/cosmos/components/modals/Send/Form.tsx
  src/plugins/cosmos/components/modals/Send/SendCommon.ts
  src/plugins/cosmos/components/modals/Send/hooks/useFormSend/useFormSend.test.tsx
  src/plugins/cosmos/components/modals/Send/hooks/useFormSend/useFormSend.tsx
  src/plugins/cosmos/components/modals/Send/views/Confirm.tsx
  src/plugins/cosmos/components/modals/Send/views/Details.tsx
Labels: beta

#2986 feat: delete and unify cosmos send form modal
  src/components/Modals/Send/Send.tsx
  src/components/Modals/Send/views/Confirm.tsx
  src/components/Modals/Send/views/Details.tsx
  src/plugins/cosmos/components/modals/Send/Form.tsx
  src/plugins/cosmos/components/modals/Send/views/Confirm.tsx
  src/plugins/cosmos/components/modals/Send/views/Details.tsx
Labels: beta

#2987 fix: send details - asset selection back button
  src/components/Modals/Send/Form.tsx
  src/components/SelectAssets/SelectAssetRouter.tsx
  src/components/SelectAssets/SelectAssetView.tsx
  src/components/SelectAssets/SelectAssets.tsx
Labels: beta

#3009 feat: fiat ramp multi account
  src/components/Modals/FiatRamps/components/FiatRampButton.tsx
  src/components/Modals/FiatRamps/views/Manager.tsx
  src/components/Modals/FiatRamps/views/Overview.tsx
  src/state/slices/portfolioSlice/selectors.ts
Labels: multiple accounts, beta

#3023 fix: fox and foxy balances on fox page respect multiple accounts
  src/plugins/foxPage/foxPage.tsx
  src/state/slices/portfolioSlice/selectors.ts
Labels: beta

#3027 fix: cosmos asset account allocation
  src/components/AssetAccounts/AssetAccountRow.tsx
  src/components/AssetHeader/AssetChart.tsx
  src/state/slices/accountSpecifiersSlice/selectors.ts
  src/state/slices/portfolioSlice/selectors.ts
Labels: beta

#3048 feat: subscribe txs by accountid, multi account support
  src/context/TransactionsProvider/TransactionsProvider.tsx
  src/state/slices/portfolioSlice/portfolioSliceCommon.ts
Labels: beta

#3054 chore: add `bip44Params` to idle
  package.json
  src/features/defi/providers/idle/components/IdleManager/Claim/components/Confirm.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Approve.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Confirm.tsx
  yarn.lock
Labels: beta

#3063 fix: no `accountId` on asset select
  src/components/Trade/hooks/useAccountsService.tsx
Labels: beta

#3071 chore: cosmos sdk selector rationalization
  src/components/Bridge/BridgeRoutes/Confirm.tsx
  src/components/Delegate/StakingOpportunities.tsx
  src/components/StakingVaults/AllEarnOpportunities.tsx
  src/components/Trade/AssetAccountRow.tsx
  src/components/Trade/TradeInput.tsx
  src/components/Trade/hooks/useAccountsService.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Overview/CosmosOverview.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Overview/WithdrawCard.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Withdraw/components/Withdraw.tsx
  src/features/defi/providers/idle/components/IdleManager/Claim/components/Status.tsx
  src/features/defi/providers/idle/components/IdleManager/Deposit/components/Status.tsx
  src/features/defi/providers/idle/components/IdleManager/Withdraw/components/Status.tsx
  src/pages/Defi/hooks/__snapshots__/useCosmosStakingBalances.test.tsx.snap
  src/pages/Defi/hooks/useCosmosSdkStakingBalances.tsx
  src/pages/Defi/hooks/useCosmosStakingBalances.test.tsx
  src/state/slices/accountSpecifiersSlice/selectors.ts
  src/state/slices/portfolioSlice/portfolioSlice.test.ts
  src/state/slices/portfolioSlice/selectors.ts
  src/state/slices/txHistorySlice/utils.ts
Labels: beta

#2481 feat: fox lp / farms RTK queries refactor
  src/components/StakingVaults/AllEarnOpportunities.tsx
  src/components/StakingVaults/EarnOpportunities.tsx
  src/components/Trade/hooks/useSwapper/useSwapper.test.tsx
  src/components/Trade/hooks/useTradeRoutes/useTradeRoutes.test.tsx
  src/context/FoxEthProvider/FoxEthProvider.tsx
  src/features/defi/contexts/DefiManagerProvider/DefiCommon.ts
  src/features/defi/contexts/DefiManagerProvider/DefiManagerProvider.tsx
  src/features/defi/helpers/normalizeOpportunity.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/FoxEthLpDeposit.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Deposit/components/Status.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Overview/FoxEthLpOverview.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/FoxEthLpWithdraw.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Status.tsx
  src/features/defi/providers/fox-eth-lp/components/FoxEthLpManager/Withdraw/components/Withdraw.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/FoxFarmingDeposit.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimConfirm.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimRoutes.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/Claim/ClaimStatus.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Overview/FoxFarmingOverview.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/FoxFarmingWithdraw.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/fox-farming/components/FoxFarmingManager/Withdraw/components/Withdraw.tsx
  src/hooks/useBalanceChartData/useBalanceChartData.ts
  src/pages/Dashboard/Portfolio.tsx
  src/pages/Dashboard/PortfolioBreakdown.tsx
  src/pages/Defi/components/OpportunityCard.tsx
  src/pages/Defi/components/OverviewHeader.tsx
  src/pages/Defi/hooks/useEarnBalances.tsx
  src/pages/Defi/views/Overview.tsx
  src/pages/Defi/views/StakingVaults.tsx
  src/plugins/foxPage/hooks/useDefiOpportunity.ts
  src/plugins/foxPage/hooks/useFarmingApr.ts
  src/plugins/foxPage/hooks/useLpApr.ts
  src/plugins/foxPage/hooks/useOtherOpportunities.ts
  src/state/reducer.ts
  src/state/slices/foxEthSlice/constants.ts
  src/state/slices/foxEthSlice/contractManager.ts
  src/state/slices/foxEthSlice/foxEthCommon.ts
  src/state/slices/foxEthSlice/foxEthSlice.ts
  src/state/slices/foxEthSlice/selectors.ts
  src/state/slices/foxEthSlice/types.ts
  src/state/slices/foxEthSlice/utils.ts
  src/state/slices/marketDataSlice/marketDataSlice.tsx
  src/state/slices/portfolioSlice/selectors.ts
  src/state/slices/selectors.ts
  src/state/store.ts
  src/test/mocks/store.ts
Labels: cleanup

#3120 chore: enable cowswap flag
  .env.base
Labels: cleanup

#3140 feat: wallet connect modal
  src/assets/translations/en/main.json
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/SideNavContent.tsx
  src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
  src/plugins/walletConnectToDapps/components/modal/SignMessageConfirmation.tsx
  src/plugins/walletConnectToDapps/components/modal/WalletConnectModal.tsx
  src/plugins/walletConnectToDapps/components/modal/WalletSummaryCard.tsx
Labels: cleanup

#3143 feat: walletconnect gas price input
  src/assets/translations/en/main.json
  src/components/AccountDropdown/AccountDropdown.tsx
  src/components/DeFi/components/GasInput.tsx
  src/components/Modals/Send/TxFeeRadioGroup.tsx
  src/plugins/walletConnectToDapps/components/modal/ModalSection.tsx
  src/plugins/walletConnectToDapps/components/modal/SignMessageConfirmation.tsx
  src/plugins/walletConnectToDapps/components/modal/SignTransactionAdvancedParameters.tsx
Labels: cleanup

#3139 feat: opportunity slice AccountId selectors
  src/state/selectors.ts
  src/state/slices/opportunitiesSlice/constants.ts
  src/state/slices/opportunitiesSlice/mocks.ts
  src/state/slices/opportunitiesSlice/opportunitiesSlice.test.ts
  src/state/slices/opportunitiesSlice/opportunitiesSlice.ts
  src/state/slices/opportunitiesSlice/selectors.test.ts
  src/state/slices/opportunitiesSlice/selectors.ts
  src/state/slices/opportunitiesSlice/utils.ts
Labels: cleanup
