Repository shapeshift/web, pull requests merged in 2024-04, with the labels that each got.

#6431 feat: move dynamic Ledger feature-detection to walletSupportsChain
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
  src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
  src/components/StakingVaults/PositionTable.tsx
  src/components/StakingVaults/ProviderCard.tsx
  src/context/AppProvider/AppContext.tsx
  src/hooks/useWalletSupportsChain/useWalletSupportsChain.ts
  src/pages/Lending/hooks/useLendingSupportedAssets/index.ts
  src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
  src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
  src/plugins/walletConnectToDapps/components/modals/SessionProposal.tsx
  src/state/slices/portfolioSlice/selectors.ts
Labels: high risk, ledger

#6551 feat: add bottom sheet dialog
  package.json
  src/components/AssetSearch/AssetSearch.tsx
  src/components/Input/Input.theme.ts
  src/components/Layout/Page.tsx
  src/components/Modal/components/Dialog.tsx
  src/components/Modal/components/DialogBackButton.tsx
  src/components/Modal/components/DialogBody.tsx
  src/components/Modal/components/DialogCloseButton.tsx
  src/components/Modal/components/DialogFooter.tsx
  src/components/Modal/components/DialogHeader.tsx
  src/components/Modal/components/DialogScroll.tsx
  src/components/Modal/components/DialogTitle.tsx
  src/components/Modals/AssetSearch/AssetSearchModal.tsx
  src/components/Modals/Receive/Receive.tsx
  src/components/Modals/Receive/ReceiveInfo.tsx
  src/components/Modals/Send/AddressInput/AddressInput.tsx
  src/components/Modals/Send/Form.tsx
  src/components/Modals/Send/Send.tsx
  src/components/Modals/Send/views/Address.tsx
  src/components/Modals/Send/views/Confirm.tsx
  src/components/Modals/Send/views/Details.tsx
  src/components/Modals/TradeAssetSearch/TradeAssetSearchModal.tsx
  src/components/QrCodeScanner/QrCodeScanner.tsx
  src/components/SelectAssets/SelectAssets.tsx
  src/components/TradeAssetSearch/TradeAssetSearch.tsx
  src/components/TradeAssetSearch/components/GroupedAssetList/GroupedAssetList.tsx
  src/context/DialogContextProvider/DialogContextProvider.tsx
  src/index.tsx
  src/theme/theme.tsx
  yarn.lock
Labels: high risk

#6626 feat: use proxy validation endpoint
  packages/chain-adapters/src/cosmossdk/CosmosSdkBaseAdapter.ts
  packages/chain-adapters/src/cosmossdk/cosmos/CosmosChainAdapter.ts
  packages/chain-adapters/src/cosmossdk/thorchain/ThorchainChainAdapter.ts
  packages/chain-adapters/src/evm/EvmBaseAdapter.ts
  packages/chain-adapters/src/evm/arbitrum/ArbitrumChainAdapter.test.ts
  packages/chain-adapters/src/evm/arbitrumNova/ArbitrumNovaChainAdapter.test.ts
  packages/chain-adapters/src/evm/avalanche/AvalancheChainAdapter.test.ts
  packages/chain-adapters/src/evm/bnbsmartchain/BscChainAdapter.test.ts
  packages/chain-adapters/src/evm/ethereum/EthereumChainAdapter.test.ts
  packages/chain-adapters/src/evm/gnosis/GnosisChainAdapter.test.ts
  packages/chain-adapters/src/evm/polygon/PolygonChainAdapter.test.ts
  packages/chain-adapters/src/utils/validateAddress.ts
  packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
  packages/chain-adapters/src/utxo/bitcoin/BitcoinChainAdapter.test.ts
  packages/chain-adapters/src/utxo/bitcoincash/BitcoinCashChainAdapter.test.ts
  packages/chain-adapters/src/utxo/dogecoin/DogecoinChainAdapter.test.ts
  packages/chain-adapters/src/utxo/litecoin/LitecoinChainAdapter.test.ts
  react-app-rewired/headers/csps/shapeshiftProxy.ts
  react-app-rewired/headers/csps/trmLabs.ts
Labels: high risk

#6624 feat: thorchain LP charts
  package.json
  src/components/SimpleChart.tsx
  src/pages/ThorChainLP/Pool/Pool.tsx
  src/pages/ThorChainLP/Pool/components/PoolChart.tsx
  src/react-queries/queries/midgard.ts
  yarn.lock
Labels: beard-oil

#6338 perf: various rendering performance improvements
  src/components/AssetAccounts/AssetAccountRow.tsx
  src/components/AssetHeader/AssetChart.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/NavBar/MainNavLink.tsx
  src/components/Layout/Header/NavBar/NavBar.tsx
  src/components/Layout/Header/SideNavContent.tsx
  src/components/Modals/FiatRamps/FiatRampsModal.tsx
  src/components/Modals/Nfts/NftModal.tsx
  src/components/Modals/PopupWindowModal.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/TimeRemaining.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useAllowanceApproval.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useApprovalTx.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useCountdown.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalNeeded.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useTradeExecution.tsx
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/MultiHopTrade/components/TradeInput/components/CollapsibleQuoteList.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/CountdownSpinner.tsx
  src/components/MultiHopTrade/components/TradeInput/components/WithLazyMount.tsx
  src/components/MultiHopTrade/components/TradeInput/hooks/useSharedHieght.tsx
  src/components/MultiHopTrade/hooks/quoteValidation/usePriceImpact.tsx
  src/components/MultiHopTrade/hooks/useAccountIds.tsx
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/hooks.tsx/useGetSwapperTradeQuote.tsx
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
  src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
  src/components/Nfts/hooks/useNfts.tsx
  src/components/PriceChart/PriceChart.tsx
  src/components/StakingVaults/hooks/useFetchOpportunities.tsx
  src/components/TradeAssetSearch/Chains/ChainCard.tsx
  src/hooks/useEvm/useEvm.ts
  src/hooks/useFetchPriceHistories/useFetchPriceHistories.ts
  src/hooks/useHasFocus.tsx
  src/hooks/useIsSmartContractAddress/useIsSmartContractAddress.ts
  src/hooks/usePoll/usePoll.tsx
  src/pages/Accounts/components/AccountNumberRow.tsx
  src/pages/ThorChainLP/queries/hooks/useAllUserLpData.ts
  src/pages/TransactionHistory/DownloadButton.tsx
  src/plugins/walletConnectToDapps/hooks/useIsWalletConnectToDappsSupportedWallet.tsx
Labels: high risk

#6647 feat: use WarningAcknowledgement component
  src/assets/translations/en/main.json
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Footer.tsx
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/WarningAcknowledgement/WarningAcknowledgement.tsx
  src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
  src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
Labels: high risk

#6725 feat: import accounts drawer
  src/assets/translations/en/main.json
  src/components/AccountDetails.tsx
  src/components/AccountDropdown/AccountDropdown.tsx
  src/components/AssetAccounts/AssetAccountRow.tsx
  src/components/AssetHeader/AccountLabel.tsx
  src/components/ChainDropdown/ChainRow.tsx
  src/components/Equity/EquityAccountRow.tsx
  src/components/Equity/EquityRow.tsx
  src/components/ImportAccountsDrawer/ImportAccountsDrawer.tsx
  src/components/Layout/Header/DegradedStateBanner.tsx
  src/components/Layout/Header/GlobalSearch/ActionResults/ActionResult.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
  src/components/MiddleEllipsis/MiddleEllipsis.tsx
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
  src/components/TradeAssetSearch/Chains/ChainCard.tsx
  src/features/defi/providers/fox-farming/hooks/useFoxFarming.ts
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
  src/lib/utils/accounts.test.ts
  src/lib/utils/accounts.ts
  src/lib/utils/index.test.ts
  src/lib/utils/index.ts
  src/lib/utils/thorchain/balance.ts
  src/lib/utils/thorchain/index.ts
  src/lib/utils/thorchain/lending.ts
  src/lib/utils/thorchain/lp.ts
  src/lib/utils/utxo.ts
  src/pages/Accounts/Account.tsx
  src/pages/Accounts/AccountTxHistory.tsx
  src/pages/Accounts/components/AccountEntryRow.tsx
  src/pages/Accounts/components/AccountNumberRow.tsx
  src/pages/Accounts/components/ChainRow.tsx
  src/pages/Dashboard/components/ErroredTxHistoryAccounts.tsx
  src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
  src/pages/Lending/hooks/useIsSweepNeededQuery.ts
  src/pages/ThorChainLP/queries/queries.ts
  src/plugins/walletConnectToDapps/components/header/AddressLinks.tsx
  src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx
  src/react-queries/index.ts
  src/react-queries/queries/accountManagement.ts
  src/state/slices/assetsSlice/assetsSlice.ts
  src/state/slices/opportunitiesSlice/resolvers/cosmosSdk/index.ts
  src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
  src/state/slices/portfolioSlice/selectors.ts
  src/state/slices/portfolioSlice/utils.test.ts
  src/state/slices/portfolioSlice/utils.ts
Labels: high risk

#6731 feat: add l1tolongtail to the thorchain swapper
  .env.base
  .env.dev
  src/components/MultiHopTrade/helpers.ts
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
  src/config.ts
  src/lib/swapper/swappers/ThorchainSwapper/constants.ts
  src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
  src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.test.ts
  src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/addAggregatorAndDestinationToMemo.test.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/addAggregatorAndDestinationToMemo.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/addSlippageToMemo.test.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/getBestAggregator.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/getL1ToLongtailQuote.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/getL1quote.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/longTailHelpers.ts
  src/lib/utils/index.ts
  src/state/slices/preferencesSlice/preferencesSlice.ts
  src/test/mocks/store.ts
Labels: high risk
