Repository shapeshift/web, pull requests merged in 2024-01, with the labels that each got.

#6029 chore: add risk comments
  .github/PULL_REQUEST_TEMPLATE.md
Labels: high risk

#6035 chore: clean up of trade related slices and selectors
  src/components/FeeExplainer/FeeExplainer.tsx
  src/components/MultiHopTrade/MultiHopTrade.tsx
  src/components/MultiHopTrade/components/FeeModal/FeeBreakdown.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/MultiHopTradeConfirm.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/Footer.tsx
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/hooks/useIsApprovalInitiallyNeeded.tsx
  src/components/MultiHopTrade/components/SlippagePopover.tsx
  src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/MultiHopTrade/components/TradeInput/components/ManualAddressEntry.tsx
  src/components/MultiHopTrade/components/TradeInput/components/SellAssetInput.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
  src/components/MultiHopTrade/components/TradeInput/getQuoteErrorTranslation.ts
  src/components/MultiHopTrade/components/TradeInput/getQuoteRequestErrorTranslation.ts
  src/components/MultiHopTrade/components/TradeSuccess/TradeSuccess.tsx
  src/components/MultiHopTrade/components/VerifyAddresses/VerifyAddresses.tsx
  src/components/MultiHopTrade/helpers.ts
  src/components/MultiHopTrade/hooks/quoteValidation/usePriceImpact.tsx
  src/components/MultiHopTrade/hooks/useAccountIds.tsx
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
  src/components/MultiHopTrade/hooks/useHopHelper.tsx
  src/components/MultiHopTrade/hooks/useIsTradingActive.tsx
  src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
  src/components/MultiHopTrade/hooks/useSupportedAssets.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
  src/state/apis/swapper/getIsTradingActiveApi.ts
  src/state/apis/swapper/helpers/getInputOutputRatioFromQuote.test.ts
  src/state/apis/swapper/helpers/getInputOutputRatioFromQuote.ts
  src/state/apis/swapper/helpers/testData.ts
  src/state/apis/swapper/helpers/validateQuoteRequest.ts
  src/state/apis/swapper/helpers/validateTradeQuote.ts
  src/state/apis/swapper/index.ts
  src/state/apis/swapper/selectors.ts
  src/state/apis/swapper/swapperApi.ts
  src/state/apis/swapper/types.ts
  src/state/apis/swappers/selectors.ts
  src/state/apis/swappers/swappersApi.ts
  src/state/reducer.ts
  src/state/slices/selectors.ts
  src/state/slices/swappersSlice/selectors.ts
  src/state/slices/tradeInputSlice/selectors.ts
  src/state/slices/tradeInputSlice/tradeInputSlice.ts
  src/state/slices/tradeQuoteSlice/selectors.ts
  src/state/store.ts
  src/test/mocks/store.ts
Labels: high risk

#6052 fix: add amountOutMin to longtail
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/HopTransactionStep.tsx
  src/components/MultiHopTrade/components/TradeConfirm/ReceiveSummary.tsx
  src/components/MultiHopTrade/components/TradeConfirm/TradeConfirm.tsx
  src/lib/getTxLink.ts
  src/lib/swapper/swappers/ThorchainSwapper/constants.ts
  src/lib/swapper/swappers/ThorchainSwapper/endpoints.ts
  src/lib/swapper/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/getL1quote.ts
  src/lib/swapper/swappers/ThorchainSwapper/utils/getLongtailQuote.ts
  src/state/apis/swapper/swapperApi.ts
Labels: high risk

#6051 feat: async quote loading
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuote.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/TradeQuotes.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/TradeQuoteCard.tsx
  src/components/MultiHopTrade/components/TradeInput/components/TradeQuotes/components/TradeQuoteContent.tsx
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/getTradeQuoteArgs.ts
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/hooks.tsx/useGetSwapperTradeQuote.tsx
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Overview/ThorchainSaversOverview.tsx
  src/lib/swapper/constants.ts
  src/lib/swapper/swapper.ts
  src/lib/swapper/swappers/LifiSwapper/getTradeQuote/getTradeQuote.ts
  src/lib/swapper/tradeExecution.ts
  src/lib/swapper/utils.ts
  src/state/apis/swapper/helpers/validateQuoteRequest.ts
  src/state/apis/swapper/selectors.ts
  src/state/apis/swapper/swapperApi.ts
  src/state/apis/swapper/types.ts
  src/state/slices/tradeInputSlice/selectors.ts
  src/state/slices/tradeQuoteSlice/constants.ts
  src/state/slices/tradeQuoteSlice/helpers.ts
  src/state/slices/tradeQuoteSlice/selectors.ts
  src/state/slices/tradeQuoteSlice/tradeQuoteSlice.ts
  src/test/mocks/store.ts
Labels: high risk

#6081 fix: regression of smart contract sell address checks on validateTradeQuote
  src/state/apis/swapper/helpers/validateTradeQuote.ts
  src/state/apis/swapper/swapperApi.ts
Labels: high-priority, high risk

#6084 feat: thorchain LP deposits
  src/lib/swapper/swappers/ThorchainSwapper/evm/routerCallData.test.ts
  src/lib/swapper/swappers/ThorchainSwapper/evm/utils/getThorTxData.ts
  src/lib/utils/thorchain/constants.ts
  src/lib/utils/thorchain/index.ts
  src/lib/utils/thorchain/lp.ts
  src/lib/utils/thorchain/lp/types.ts
  src/lib/utils/thorchain/routerCalldata.ts
  src/pages/ThorChainLP/components/AddLiquitity/AddLiquidity.tsx
  src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
  src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
  src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
  src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
  src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
  src/pages/ThorChainLP/queries/hooks/useAllUserLpData.ts
  src/pages/ThorChainLP/queries/hooks/useUserLpData.ts
  src/pages/ThorChainLP/queries/queries.ts
  src/react-queries/index.ts
Labels: thorchain-lp

#6101 fix: thorchain LP deposit invalidation
  src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
Labels: thorchain-lp

#6102 fix: lp deposit balance checks
  src/pages/ThorChainLP/components/AddLiquitity/AddLiquidityInput.tsx
Labels: thorchain-lp
