Repository shapeshift/web, pull requests merged in 2024-03, with the labels that each got.

#6285 feat: lp withdrawal tx logic
  src/components/Modals/QrCode/Form.tsx
  src/components/Modals/Send/Form.tsx
  src/components/Modals/Send/SendCommon.tsx
  src/components/Modals/Send/hooks/useFormSend/useFormSend.test.tsx
  src/components/Modals/Send/hooks/useFormSend/useFormSend.tsx
  src/components/Modals/Send/hooks/useSendDetails/useSendDetails.test.tsx
  src/components/Modals/Send/hooks/useSendDetails/useSendDetails.tsx
  src/components/Modals/Send/hooks/useSendFees/useSendFees.tsx
  src/components/Modals/Send/utils.ts
  src/components/Modals/Send/views/Confirm.tsx
  src/components/Modals/Send/views/Details.tsx
  src/components/Sweep.tsx
  src/features/defi/providers/cosmos/components/CosmosManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Confirm.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Deposit/components/Deposit.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Confirm.tsx
  src/features/defi/providers/thorchain-savers/components/ThorchainSaversManager/Withdraw/components/Withdraw.tsx
  src/lib/utils/thorchain/balance.ts
  src/lib/utils/thorchain/lp/types.ts
  src/lib/utils/thorchain/lp/utils.ts
  src/pages/Lending/Pool/components/Borrow/BorrowConfirm.tsx
  src/pages/Lending/Pool/components/Borrow/BorrowInput.tsx
  src/pages/Lending/Pool/components/Repay/RepayConfirm.tsx
  src/pages/Lending/hooks/useGetEstimatedFeesQuery.ts
  src/pages/ThorChainLP/components/AddLiquidity/AddLiquidityInput.tsx
  src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidity.tsx
  src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquidityInput.tsx
  src/pages/ThorChainLP/components/RemoveLiquidity/RemoveLiquiditySweep.tsx
  src/pages/ThorChainLP/components/RemoveLiquidity/types.ts
  src/pages/ThorChainLP/components/ReusableLpConfirm.tsx
  src/pages/ThorChainLP/components/ReusableLpStatus/ReusableLpStatus.tsx
  src/pages/ThorChainLP/components/ReusableLpStatus/TransactionRow.tsx
  src/react-queries/hooks/useQuoteEstimatedFeesQuery.ts
  src/state/slices/opportunitiesSlice/resolvers/thorchainsavers/utils.ts
Labels: high risk

#6327 perf: dont fetch staking opportunities on app boot
  src/components/Layout/Header/GlobalSearch/GlobalSearchModal.tsx
  src/components/Layout/Header/GlobalSearch/LpResults/LpResult.tsx
  src/components/Layout/Header/GlobalSearch/LpResults/LpResults.tsx
  src/components/Layout/Header/GlobalSearch/SearchResults.tsx
  src/components/Layout/Header/GlobalSearch/StakingResults/StakingResult.tsx
  src/components/Layout/Header/GlobalSearch/StakingResults/StakingResults.tsx
  src/components/Layout/Header/GlobalSearch/utils.ts
  src/components/Nfts/NftTable.tsx
  src/components/Nfts/hooks/useFetchNfts.tsx
  src/components/StakingVaults/hooks/useFetchOpporunities.tsx
  src/context/AppProvider/AppContext.tsx
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Dashboard/components/DashboardHeader.tsx
  src/pages/Dashboard/components/ProfileAvatar/AvatarSelectModal.tsx
  src/pages/Defi/views/StakingVaults.tsx
  src/state/apis/nft/nftApi.ts
  src/state/apis/nft/selectors.ts
  src/state/slices/search-selectors.ts
Labels: high risk

#6362 fix: add mtpelerin integration key and currencies
  .env.base
  packages/caip/src/adapters/mtpelerin/index.ts
  src/components/Modals/FiatRamps/fiatRampProviders/mtpelerin.ts
  src/config.ts
Labels: bug

#6454 feat: render AvailablePools as ReactTable
  src/components/Table/Table.theme.ts
  src/pages/ThorChainLP/AvailablePools.tsx
  src/pages/ThorChainLP/components/PoolIcon.tsx
  src/pages/ThorChainLP/components/PoolsHeader.tsx
Labels: beard-oil, nice to have

#6459 feat: thorchain lp render YourPositions with ReactTable
  src/pages/ThorChainLP/YourPositions.tsx
Labels: beard-oil, nice to have, thorchain-lp

#6470 feat: thorchain LP expose volumeStats union in pool query-wrapper
  src/pages/ThorChainLP/AvailablePools.tsx
  src/pages/ThorChainLP/queries/hooks/usePool.ts
  src/pages/ThorChainLP/queries/hooks/usePools.ts
Labels: thorchain-lp

#6344 feat: enable thorchain lp
  .env.base
  .env.dev
  .env.develop
Labels: thorchain-lp

#6452 fix: allow manual address for unsupported buy asset
  src/components/MultiHopTrade/components/TradeInput/TradeInput.tsx
  src/components/MultiHopTrade/hooks/useGetTradeQuotes/useGetTradeQuotes.tsx
Labels: keepkey, high risk

#6498 fix: update fox discount threshold from 1M to 300k
  src/lib/fees/parameters/swapper.ts
Labels: high risk

#6491 fix: thorchain LP UTXO deposits with Ledger
  packages/chain-adapters/src/utxo/UtxoBaseAdapter.ts
  src/lib/utils/thorchain/index.ts
  src/setupVitest.ts
Labels: high risk, ledger
