Repository shapeshift/web, pull requests merged in 2025-01, with the labels that each got.

#8399 perf: market data benchmarking outcomes
  src/context/AppProvider/AppContext.tsx
  src/lib/asset-service/service/AssetService.ts
  src/lib/portals/utils.ts
  src/state/slices/assetsSlice/assetsSlice.ts
  src/state/slices/marketDataSlice/marketDataSlice.tsx
Labels: high risk

#8461 fix: broken exhaustiveness checks in switch statements
  packages/contracts/src/ethersProviderSingleton.ts
  packages/swapper/src/swappers/ArbitrumBridgeSwapper/utils/fetchArbitrumBridgeSwap.ts
  packages/swapper/src/swappers/ThorchainSwapper/getThorTradeQuote/getTradeQuote.ts
  packages/swapper/src/swappers/ThorchainSwapper/getThorTradeRate/getTradeRate.ts
  packages/swapper/src/swappers/ThorchainSwapper/utils/checkOutputTxConfirmations.ts
  packages/swapper/src/swappers/ThorchainSwapper/utils/getL1Rate.ts
  packages/swapper/src/swappers/ThorchainSwapper/utils/getL1quote.ts
  packages/swapper/src/swappers/ThorchainSwapper/utils/getLatestThorTxStatusMessage.ts
  packages/utils/src/chainIdToFeeAssetId.ts
  src/components/MultiHopTrade/components/MultiHopTradeConfirm/components/ApprovalStep/ApprovalStep.tsx
  src/state/slices/limitOrderInputSlice/helpers.ts
  src/state/slices/limitOrderInputSlice/limitOrderInputSlice.ts
Labels: mental health

#8519 fix: wallet state corruption round 4
  src/components/ManageAccountsDrawer/components/ImportAccounts.tsx
  src/components/MultiHopTrade/hooks/useReceiveAddress.tsx
  src/context/WalletProvider/KeepKey/components/Passphrase.tsx
  src/context/WalletProvider/KeepKey/components/Pin.tsx
  src/context/WalletProvider/Ledger/components/Chains.tsx
  src/context/WalletProvider/NativeWallet/components/EnterPassword.tsx
  src/context/WalletProvider/NativeWallet/components/NativeLoad.tsx
  src/context/WalletProvider/NativeWallet/hooks/useNativeEventHandler.ts
  src/context/WalletProvider/WalletConnectV2/useWalletConnectV2EventHandler.ts
  src/context/WalletProvider/WalletProvider.tsx
  src/context/WalletProvider/WalletViewsSwitch.tsx
  src/context/WalletProvider/actions.ts
  src/pages/Accounts/AddAccountModal.tsx
Labels: high risk, max-pain

#8557 feat: virtualized assets page
  package.json
  src/components/MarketsTableVirtualized.tsx
  src/components/StakingVaults/Cells.tsx
  src/pages/Assets/Assets.tsx
  yarn.lock
Labels: beard-oil
